"""
Week 3 Day 4 — Response Formatting & Probabilistic Framing Node
===============================================================
Synthesizes verified tool results into structured, user-facing markdown responses:
1. Predictions: Formats calibrated win probabilities, confidence tiers, expected margins,
   top 2-3 feature drivers, and mandatory probabilistic model disclaimers.
2. Retrievals: Presents exact, audited historical tables with verified statistics.
3. Factual: Authoritative AFL domain knowledge citations.
4. Refusals: Polite off-topic guardrail redirection back to AFL topics.
5. Clarifications: Friendly follow-up questions for ambiguous inputs.
"""

from typing import Dict, Any, List
from src.state import AFLGraphState

DISCLAIMER_TEXT = (
    "\n\n> ⚠️ **Probabilistic Model Disclaimer:** *AFL match and player forecasts are "
    "calibrated statistical estimations generated by Machine Learning models using historical "
    "performance differentials, venue trends, and rolling form. Sports outcomes are inherently dynamic "
    "and uncertain; predictions should be treated as probabilistic insights, not guaranteed results.*"
)


class AFLResponseFormatter:
    """Formats final responses according to intent and validation status."""

    @staticmethod
    def format_prediction(tool_res: Dict[str, Any]) -> str:
        model_type = tool_res.get("model_type", "match_winner")

        if model_type == "match_winner":
            home = tool_res.get("home_team", "").title()
            away = tool_res.get("away_team", "").title()
            winner = tool_res.get("predicted_winner", "").title()
            prob = tool_res.get("win_probability", 0.5) * 100
            conf = tool_res.get("confidence_level", "Moderate")
            margin = tool_res.get("expected_margin_range", "1 to 12 points")
            venue = tool_res.get("venue", "AFL Venue")
            date = tool_res.get("match_date", "Upcoming")
            drivers = tool_res.get("key_drivers", [])

            # Format top 2-3 drivers
            drivers_md = ""
            for d in drivers[:3]:
                drivers_md += f"- {d}\n"

            response = (
                f"### 🏉 AFL Match Prediction: {home} vs {away}\n\n"
                f"**Fixture Context:** {date} at {venue}\n\n"
                f"- **Projected Winner:** **{winner}**\n"
                f"- **Win Probability:** **{prob:.1f}%** ({conf})\n"
                f"- **Expected Margin Range:** {margin}\n\n"
                f"#### 📊 Key Feature Drivers Driving Model Forecast:\n"
                f"{drivers_md}"
                f"{DISCLAIMER_TEXT}"
            )
            return response

        elif model_type == "top_player":
            team = (tool_res.get("query_team") or tool_res.get("team") or "AFL Team").title()
            opp = tool_res.get("opponent")
            opp_str = f" vs {opp.title()}" if opp else ""
            stat = tool_res.get("stat_type", "disposals").replace("_", " ").title()
            ranked = tool_res.get("ranked_players", [])

            table_rows = ""
            for p in ranked[:5]:
                table_rows += f"| {p.get('rank', '-')} | **{p.get('player_name', 'Player')}** | {p.get('projected_stat', 0.0):.1f} | {p.get('season_avg', 0.0):.1f} | {p.get('recent_form_3', 0.0):.1f} |\n"

            response = (
                f"### 🌟 Projected Top Performers ({stat}): {team}{opp_str}\n\n"
                f"Model projections based on rolling form, opponent defensive rating, and venue history:\n\n"
                f"| Rank | Player Name | Projected {stat} | 2024 Season Avg | Last 3-Game Form |\n"
                f"| :--- | :--- | :--- | :--- | :--- |\n"
                f"{table_rows}\n"
                f"- **Top Projected Performer:** **{ranked[0]['player_name']}** ({ranked[0]['projected_stat']:.1f} projected {stat.lower()})\n"
                f"- **Projection Grounding:** Form weighted at 60%, opponent matchup difficulty at 40%."
                f"{DISCLAIMER_TEXT}"
            )
            return response

        return "Prediction generated successfully."

    @staticmethod
    def format_retrieval(tool_res: Dict[str, Any]) -> str:
        ret_type = tool_res.get("retrieval_type", "general")

        if ret_type == "head_to_head":
            t_a = tool_res.get("team_a", "Team A")
            t_b = tool_res.get("team_b", "Team B")
            tot = tool_res.get("total_historical_meetings", 0)
            a_w = tool_res.get("team_a_wins", 0)
            b_w = tool_res.get("team_b_wins", 0)
            draws = tool_res.get("draws", 0)
            clashes = tool_res.get("recent_clashes", [])

            clash_rows = ""
            for c in clashes[:4]:
                clash_rows += f"| {c['date']} | R{c['round']} {c['year']} | **{c['winner']}** by {c['margin']} pts | {c['venue']} |\n"

            return (
                f"### ⚔️ AFL Head-to-Head Record: {t_a} vs {t_b}\n\n"
                f"- **Total Historical Clashes:** {tot}\n"
                f"- **Analyzed Recent Record:** {t_a} {a_w} – {b_w} {t_b}" + (f" ({draws} Draws)" if draws > 0 else "") + "\n\n"
                f"#### Recent Meetings:\n"
                f"| Date | Round | Result & Margin | Venue |\n"
                f"| :--- | :--- | :--- | :--- |\n"
                f"{clash_rows}"
            )

        elif ret_type == "player_round":
            p_name = tool_res.get("player_name", "Player")
            rnd = tool_res.get("round", "-")
            season = tool_res.get("season", 2024)
            team = tool_res.get("team", "Club")
            opp = tool_res.get("opponent", "Opponent")
            disp = tool_res.get("disposals", 0)
            goals = tool_res.get("goals", 0)
            fant = tool_res.get("fantasy_points", 0)
            date = tool_res.get("match_date", "-")

            return (
                f"### 📋 Round Match Statistics: {p_name}\n\n"
                f"In **Round {rnd}** of the **{season} AFL Season** ({date}), **{p_name}** ({team}) played against **{opp}**:\n\n"
                f"- **Disposals:** **{disp}**\n"
                f"- **Goals:** **{goals}**\n"
                f"- **AFL Fantasy Points:** **{fant}**\n"
            )

        elif ret_type == "player_season":
            p_name = tool_res.get("player_name", "Player")
            team = tool_res.get("team", "Club")
            season = tool_res.get("season", 2024)
            gp = tool_res.get("games_played", 0)
            tot_d = tool_res.get("total_disposals", 0)
            avg_d = tool_res.get("avg_disposals", 0.0)
            tot_g = tool_res.get("total_goals", 0)
            avg_g = tool_res.get("avg_goals", 0.0)
            tot_f = tool_res.get("total_fantasy_points", 0)
            avg_f = tool_res.get("avg_fantasy_points", 0.0)

            return (
                f"### 📊 Season Performance Summary: {p_name} ({season})\n\n"
                f"**{p_name}** represented **{team}** across **{gp} games** during the {season} season:\n\n"
                f"| Metric | Season Total | Per Game Average |\n"
                f"| :--- | :--- | :--- |\n"
                f"| **Disposals** | {tot_d:.0f} | **{avg_d:.2f}** |\n"
                f"| **Goals** | {tot_g:.0f} | **{avg_g:.2f}** |\n"
                f"| **Fantasy Points** | {tot_f:.0f} | **{avg_f:.2f}** |\n"
            )

        elif ret_type == "team_form":
            team = tool_res.get("team", "Club")
            season = tool_res.get("season", 2024)
            rec = tool_res.get("recent_record", "-")
            matches = tool_res.get("matches", [])

            m_rows = ""
            for m in matches[:4]:
                m_rows += f"| R{m['round']} | {m['date']} | vs {m['opponent']} | **{m['result']}** ({m['margin_points']} pts) | {m['venue']} |\n"

            return (
                f"### 🏉 Team Recent Form: {team} ({season})\n\n"
                f"- **Recent Record:** **{rec}** over the last {len(matches)} analyzed matches.\n\n"
                f"| Round | Date | Opponent | Outcome | Venue |\n"
                f"| :--- | :--- | :--- | :--- | :--- |\n"
                f"{m_rows}"
            )

        return "Statistical records retrieved successfully."

    @staticmethod
    def format_factual(tool_res: Dict[str, Any], query: str) -> str:
        docs = tool_res.get("documents", [])
        if not docs:
            # Fallback for factual rules or stadium knowledge
            return (
                f"### 🏉 Official AFL Domain Information\n\n"
                f"Regarding your inquiry on Australian Rules Football:\n\n"
                f"AFL matches are played on oval cricket grounds (such as the MCG, Marvel Stadium, and Adelaide Oval). "
                f"Scoring involves 6 points for a goal (kicked between the central posts) and 1 point for a behind. "
                f"For official rules and statistics, consult verified AFL feature data."
            )

        top_doc = docs[0]
        title = top_doc.get("title", "AFL Knowledge Base")
        content = top_doc.get("content", "")
        category = top_doc.get("category", "General").title()

        return (
            f"### 📖 AFL Knowledge: {title}\n"
            f"*Category: {category} | Verified Domain Knowledge*\n\n"
            f"{content}"
        )

    @staticmethod
    def format_off_topic(query: str) -> str:
        return (
            "### 🏉 AFL Footy Intelligence Assistant\n\n"
            "I specialize exclusively in **Australian Rules Football (AFL)**.\n\n"
            "I cannot assist with general topics like computer programming, culinary recipes, "
            "weather forecasts, or non-AFL sports leagues.\n\n"
            "**Here is what I can help you with:**\n"
            "- **Predict Match Winners:** *'Will the Pies beat the Cats this week?'*\n"
            "- **Project Top Players:** *'Who will top-score in disposals for the Bulldogs?'*\n"
            "- **Retrieve Exact Statistics:** *'What were Nick Daicos's stats in Round 10?'*\n"
            "- **AFL Domain Knowledge:** *'Explain the holding the ball rule' or 'What are the dimensions of the MCG?'*"
        )


def response_formatter_node(state: AFLGraphState) -> Dict[str, Any]:
    """
    LangGraph Response Formatter Node:
    Takes state, applies intent-specific formatting, ensures disclaimers on predictions,
    and produces final_response.
    """
    intent = state.get("detected_intent")
    val_status = state.get("validation_status", "valid")
    clarify_prompt = state.get("clarification_prompt")
    tool_res = state.get("tool_results")
    user_query = state.get("user_query", "")

    # Priority 1: If validation requires clarification or is unsupported, output guided prompt
    if val_status in ["needs_clarification", "unsupported", "error"] and clarify_prompt:
        final_answer = clarify_prompt
    elif intent == "off_topic":
        final_answer = AFLResponseFormatter.format_off_topic(user_query)
    elif intent == "prediction" and tool_res:
        final_answer = AFLResponseFormatter.format_prediction(tool_res)
    elif intent == "retrieval" and tool_res:
        final_answer = AFLResponseFormatter.format_retrieval(tool_res)
    elif intent == "factual" and tool_res:
        final_answer = AFLResponseFormatter.format_factual(tool_res, user_query)
    else:
        final_answer = "Your AFL request has been processed. Please specify if you need match predictions, player stats, or rules."

    # Update conversation history with AI message
    new_history = [{"role": "assistant", "content": final_answer}]

    trace_entry = {
        "node": "response_formatter_node",
        "action": "synthesize_final_response",
        "response_preview": final_answer[:120] + "..." if len(final_answer) > 120 else final_answer
    }

    return {
        "final_response": final_answer,
        "conversation_history": new_history,
        "trace": [trace_entry]
    }
